### PR TITLE
Update ElementHandle.cs

### PR DESCRIPTION
**Pull request by Mephisto090**
Change ScrollIntoViewIfNeededAsync() to a public function

### CODE REVIEW

**Comment by amaitland** [comment]
You need to add xml doc as it's now a public method.

Builds won't pass without it.

https://ci.appveyor.com/project/cefsharp/puppeteer/builds/43246685#L39

**Comment by Mephisto090** [comment]
What do you mean? This is my first time in C# and for something this big. :)

What do you mean by XML Doc?

**Comment by amaitland** [comment]
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/

**Comment by Mephisto090** [comment]
Ah I understand. I thought you were doing this `summery` since your English is better than mine.

**Pull request closed without merging**
