### PR TITLE
Random ClickAsync

### PR DESCRIPTION
**Pull request by Mephisto090**
Click the button in a random place with the new function 'ClickRandomAsync'

### CODE REVIEW

**Comment by amaitland** [comment]
Have you actually built and tested this change? 

https://ci.appveyor.com/project/cefsharp/puppeteer/builds/43246686

Before this could be considered for merge you need to
- Add new unit tests
- Refactor code as to reduce duplication.

I'm doubtful this approach will always successfully click the element as you've not validating the coordinates. 

We should adopt the same approach as puppeteer, allow the user to specify an offset.
https://github.com/puppeteer/puppeteer/blob/main/src/common/JSHandle.ts#L510

Clickablepointasync can be refactored to make it public and you can implement your own  functionality for random clicking.

**Comment by Mephisto090** [comment]
Ah I understand. The function `clickablePoint` already does what we want. It just needs to be built into the `ClickElement`. Am I correct?

**Comment by amaitland** [comment]
No, the reference is to the Google puppeteer project which is the inspiration for puppeteer Sharp which this library is based off.

**Comment by amaitland** [comment]
Closing as this doesn't compile and would likely prove to be unreliable as there's no bounds checking.

ClickablePointAsync is now public in commit https://github.com/cefsharp/Puppeteer/commit/36ee3c3f676b91831930a177fa2922e765a03c08

Between that and `ElementHandle.BoundingBoxAsync()` you should easily be able to implement your own method/extension method to click a custom point.

**Pull request closed without merging**
